### ISSUE TITLE
oTree start-up

### ISSUE THREAD

**Issue by anisfeld** [prijatelilab/PrijateliTree#1]
Purpose: Learn about and set-up oTree

As you explore oTree keep in mind that we're likely going to have two or more distinct session types.  One will involve a group of 6 users and another 2 users. 
- In the 6 person sessions we're interested in "social learning". So we'll have the users connected to each other, getting random signals and sharing information in specific ways. (something similar to this https://www.otreehub.com/projects/urn-test/)
-  The two player game we're working on details. 

- [x] Please create new tickets or a checklist of the steps to set-up oTree.

Meta-request: Let us know if there are practices for using issues that you prefer and we can have a discussion about it.

**Comment by michplunkett** [comment]
Things that I'll need from y'all to complete the initial GitHub setup:
- Then potential name for the application (it's fine if the name changes, but something other than the framework would be ideal).
- A three sentence blurb on the what the application will be, it's intended purpose, etc.
- An image that you'd like me to use for the application (either the Harris logo, UChicago logo, your lab's logo, etc.), just let me know which.
- The color template you'd like to use, or three-four colors you'd like to use for the application. I could also roll with the standard UChicago color template if you'd prefer that.

**Comment by anisfeld** [comment]
Name: PrijateliTree
Blurb: We use oTree to play lab games and collect survey data. The games provide insights into social learning, the economics of languages and other human behaviors.
Image: [The Chicago Harris logo works. ](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.crunchbase.com%2Forganization%2Fharris-school-of-public-policy-studies&psig=AOvVaw1KFRv974ltja9lJVLOc_id&ust=1693009132593000&source=images&cd=vfe&opi=89978449&ved=0CA8QjRxqFwoTCKDwztHE9oADFQAAAAAdAAAAABAE)
Colors:  @pepipandi  will send some colors or a poster with colors.

**Comment by michplunkett** [comment]
Excellent, that works! Appreciate it!
