### ISSUE TITLE
Cannot log into Heroku

### ISSUE THREAD

**Issue by anisfeld** [prijatelilab/PrijateliTree#109]
## What Issue Are You Seeing or What Feature Needs To Be Added?

@michplunkett 

I think Heroku isn't hitting the database correctly: When I try to log-in I get the following message in the logs

2023-12-20T16:56:21.035071+00:00 app[web.1]: INFO:	User submitted invalid credentials: ***** *** ****
2023-12-20T16:56:21.035665+00:00 app[web.1]: INFO:     172.59.188.52:0 - "POST /admin/login HTTP/1.1" 200 OK

I also noticed that Heroku doesn't seem to be using versioning the way you intended. It looks like every time main changes we redeploy 

![Screenshot 2023-12-20 at 10 58 43 AM](https://github.com/prijatelilab/PrijateliTree/assets/25271399/91022f05-e087-4ba1-8a72-75c37e609315)

So my hunch is that the Heroku version is not looking for the Heroku database. Hopefully this is an easy fix.

**Comment by michplunkett** [comment]
I ended up opting for every push to main in the PR as it required a bit more work than I felt it really warranted. That can be addressed if need be.
