### ISSUE TITLE
Add logic for self-selected game type

### ISSUE THREAD

**Issue by michplunkett** [prijatelilab/PrijateliTree#35]
## What Issue Are You Seeing or What Feature Needs To Be Added?

- [x] write a function to initiate a Self-Selected game ( See [create_session_games](https://github.com/prijatelilab/PrijateliTree/blob/74ac9a99571527298ea7e4c550069193be4a33d0/prijateli_tree/app/routers/administration.py#L318))
. -- We will eventually incorporate this into the session creation process, but not now.
  - A self-selected game has GameType with network=NETWORK_TYPE_SELF_SELECTED, name_hidden=False (default) 
  - The players must be initiated into the game as well such that game.players returns the 6 players. 
  -  (Reuse this [function:](https://github.com/prijatelilab/PrijateliTree/blob/74ac9a99571527298ea7e4c550069193be4a33d0/prijateli_tree/app/routers/administration.py#L363))

- [x] add a new table or update game player table to capture the network.
  - Probably best to have three columns Game id (FK) Player id (FK) and Neighbor id (FK). (Each row is a single directional relationship)
     - 1 player from each language group gets to choose 3 partners, the others get to chose 2 (you can use the players position to determine if they get 3 or 2  (e.g. position 1 and 4 get 3 neighbors).
  - We use GameUtil class access the network. We need to add code so that If the network type is NETWORK_TYPE_SELF_SELECTED, we go and pull the network 

- [x] make a GET route that allows students to pick partners (see language / layout in UX document)
- [x] make a POST route that updates the network and then sends the player to the round route.
- [x] Incorporate into existing game logic

**Comment by FedericoDM** [comment]
Progress Update @anisfeld @pepipandi:

I have created a route to allow students to choose who they want to see, along with the new required table in the DB

![image](https://github.com/prijatelilab/PrijateliTree/assets/67844597/c31f229a-0f64-4b86-8a1b-150c33a97e11)

Still to go:

- When chosen, post request to add those neighbors to the new table
- Extract those positions to game_util
- Adjust round router logic for self-selected
