### ISSUE TITLE
Need ability to create game types

### ISSUE THREAD

**Issue by michplunkett** [prijatelilab/PrijateliTree#43]

**Comment by anisfeld** [comment]
@michplunkett My thought for this is that game creation happens "automatically" as students finish the previous game. 

When the first student clicks next on `end_of_game.html`, a new game is created with all of the students in the session and we randomize game characteristics.  There can be a `game_number` and when `game_number  >=  N_games` the next button directs students to the survey. 

If that's too complicated, which it might be, we can pre-randomize all the games for a session and have the `next` button go to the next game. All of the game creation should be done without human intervention--with the possible exception of the first game. 

What do you think?

**Comment by michplunkett** [comment]
That could in theory be done, but that isn't how this was initially implemented to work. The database was setup so that you could create a game for a pre-determined number of rounds based on a particular network type (we are starting with integrated). You could then post the link for that game on several machines where the students could select their user and begin playing. The idea of sessions, automatically created games, etc. is not baked into the current architecture.

**Comment by anisfeld** [comment]
This is what we need to have done. It can be implemented with sessions or
by stringing together games.

The way the experiment works is we have 6 kids at computers for 30 min to
an hour and they play a random sequence of "games" which involves guessing
the color. Within a "game" players have multiple opportunities to guess and
update. The way Fede and I discussed these multiple guesses seemed to be
what a "round" refers to.

Each game has a network structure, bag color and anonymity condition and
all of this is  randomized--either on the spot or at the start of the
"session".  I think the network structure integrated vs segregated accept
the same underlying code so aren't that distinct.

I think it will be straight forward to implement a post request to create a
new game at the end of a game. Are there some issues you foresee with this?

I  can do that tomorrow using the current infrastructure.

**Comment by michplunkett** [comment]
Stringing together games would be easier, I can add a  NULLable column to each game that shows the `next_game` today.

**Comment by michplunkett** [comment]
The logic that will need to be fleshed out and will need your input is who gets placed in what position (are there limits on neighboring spots based on language, etc.) and who do we mark as anonymous. If you can get me that logic, it shouldn't be hard to implement.
