### ISSUE TITLE
Utilize the User's set language to present the correct text

### ISSUE THREAD

**Issue by michplunkett** [prijatelilab/PrijateliTree#47]
## What Issue Are You Seeing or What Feature Needs To Be Added?
Using the mapping of the User's language to the correct language template file and send the correct language strings to the template.

```python
template_text = languages[player.language.abbr]
```

## Are There Any Links That Would Be Helpful?
Templating: https://jinja.palletsprojects.com/en/3.1.x/templates/

**Comment by anisfeld** [comment]
Translation code is up and running in End of Game. This requires that the language table has lower case abbreviations -- which I believe is what @michplunkett intended.

<img width="597" alt="Screenshot 2023-11-18 at 5 47 31 PM" src="https://github.com/prijatelilab/PrijateliTree/assets/25271399/59509297-f656-4863-aae1-b6a19703cda9">

![Screenshot 2023-11-15 at 10 36 22 AM](https://github.com/prijatelilab/PrijateliTree/assets/25271399/a2f43859-c4d3-487e-a9cb-b772eb9d47bb)

The player objects aren't linked with languages.  @michplunkett so `languages[player.language.abbr]` doesn't work. It might be worth adjusting the models to include that backlink for languages in the game_player table. 

---

in case @FedericoDM  or @michplunkett  ends up working on templates as well. I think a good way to proceed is as follows

```
# pull the template text (or use Michael's code if we change the model)
 template_text = get_language_from_player_id(player_id, db)

# base the resulting text to the template using the key "text"
    result = {
        "request": request,
         ...
        "points": points,
        "text": template_text
    }
```

Then all our template text will have the form

`{{ text.<page/grouping>.<meaning> }}`

for example `{{ text.game_results.you_won  }}` 


Also good to know how to replace `{X}` with dynamic content:

`{{ text.real_game_intro.added_points | replace('{X}', points) }}`

**Comment by michplunkett** [comment]
They players don't, but the `User`s do. That could be fixed tho.

Regarding the language abbreviation, the abbreviations are in uppercase in the database and were in uppercase in the files. They were in sync prior to the modifications.

**Comment by anisfeld** [comment]
Cool I can adjust my local db.

In the constants doc you have lower case. Should these be upper case to or are they for some other purpose?
```
# Language Constants
LANGUAGE_ALBANIAN = "al"
LANGUAGE_ENGLISH = "en"
LANGUAGE_MACEDONIAN = "mk"
LANGUAGE_TURKISH = "tr"
```

**Comment by michplunkett** [comment]
That makes sense. Give me about 20 and I'll have your stuff in.
