### ISSUE TITLE
Add Michael as admin in Heroku project

### ISSUE THREAD

**Issue by michplunkett** [prijatelilab/PrijateliTree#5]
## What Issue Are You Seeing or What Feature Needs To Be Added?
Add Michael as an admin to the Heroku project and add a payment method so that he can setup the environments. I will set up the PostgreSQL and Deployment processes, which you will have oversight on while they are being setup, but I'll need the rights to the project to make that happen.

## Are There Any Links That Would Be Helpful?
- PostgreSQL: https://devcenter.heroku.com/articles/heroku-postgresql
- Deployment: https://devcenter.heroku.com/categories/deployment

**Comment by anisfeld** [comment]
I have added you as an admin. Let me know if you didn't get the notification.

**Comment by michplunkett** [comment]
I got it, thanks!
