### ISSUE TITLE
Create logic for next game creation

### ISSUE THREAD

**Issue by anisfeld** [prijatelilab/PrijateliTree#52]
## Are There Any Links That Would Be Helpful?

See conversation in #43

**Comment by anisfeld** [comment]
@michplunkett this code has the "logic" for next game creation. It depends on a few things / questions:

- how do you imagine the "next_game_id" being populated? I'm writing the code as if the next_game_id is None until the next game is created. 
- I'm not sure how to prevent a race between two players who press the "Next" button at the same time. Maybe it would be better to assign all the games at the beginning of session rather than through a post request?
- I write the code as if GameType includes the anonymity condition so there would be 8 game types ({integrated , segregated} x {red, blue} x {named, anonymous})  to randomly choose. (I filter to avoid self-selected).

I think I provide the logic for the next game set-up if not the exact code that will be used here. Is this enough for you to complete #43?

**Comment by michplunkett** [comment]
Hmmm.

1. That feels like the best way to go.
2. I think you could wait until all people have answered the questions and then create the game. There was a thought of creating a keep alive like function for the game, that I think could be fairly useful. That would enable you to make sure that games aren't created until ALL members have answered questions.
3. Each Player model has a `name_hidden` column that should prevent you from needing to have a different game type for that, leaving us to the 4 game types that are currently in the DB.
<img width="635" alt="Screenshot 2023-11-19 at 4 05 43 PM" src="https://github.com/prijatelilab/PrijateliTree/assets/5885605/1bd0cf73-8c9b-4145-a3be-e996e8e8ab3e">
