### ISSUE TITLE
Create Wait capability

### ISSUE THREAD

**Issue by anisfeld** [prijatelilab/PrijateliTree#53]
## What Issue Are You Seeing or What Feature Needs To Be Added?

Wait route and template (with javascript)

**Comment by michplunkett** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#supplying_request_options

**Comment by anisfeld** [comment]
Thanks for sharing `fetch()` it helped me realize that I could make a separate API  rather than reload the waiting page.

Here's the js.   
```
async function check_all_set() {
  const response = await fetch("/games/{{game_id}}/all_set");
  const all_set = await response.json();

  if (all_set.ready) {
    window.location.href = "/games/{{game_id}}/player/{{player_id}}/round";
  } else {
    console.log("still waiting ...")
  };
}

setInterval(function() { check_all_set();}, 5000);
```

**Comment by michplunkett** [comment]
Exactly! That's it.
