### ISSUE TITLE
Update language in system

### ISSUE THREAD

**Issue by anisfeld** [prijatelilab/PrijateliTree#64]
## What Issue Are You Seeing or What Feature Needs To Be Added?

The language in the .json doesn't align 100% with our design choices (e.g. highlighting Red and Blue). Other language is missing.  

- [x] Make snapshot of current webpages: @anisfeld 
- [x] Note language changes (i.e English):  
       -  Provide snippets only for new language in csv with English and Macedonian 
- [x] Get Translations

Aesthetics goals moved to #114

## Are There Any Links That Would Be Helpful?

Recall we have original [UX designs here](https://docs.google.com/document/d/1N6l2GAl8uUQKgX51PZ9GDL2JyL_eeLkoXcGWIlmDdjo/)

**Comment by FedericoDM** [comment]
I am also noting that 'Your Previous Guess' is not getting translated:


![image](https://github.com/prijatelilab/PrijateliTree/assets/67844597/23f34333-c2b7-4de6-aa13-a3a96db6576e)

**Comment by anisfeld** [comment]
@pepipandi  Here are the screen shots of the inner game loop as it is now.

I think we'll want to change the end of game language a bit to allow for colorful words! 
I'm not sure the *best* way to proceed with the language stuff, because it's not automated to go from csv to the app. 



# Start of Game

![start_of_game](https://github.com/prijatelilab/PrijateliTree/assets/25271399/23af7894-b918-4627-b1f4-7865c0ff940b)

# round 1
<img width="1512" alt="round_1" src="https://github.com/prijatelilab/PrijateliTree/assets/25271399/f41e72db-a3b1-4708-b5b1-a8a669661199">

# waiting
<img width="1512" alt="waiting" src="https://github.com/prijatelilab/PrijateliTree/assets/25271399/58718cbc-2713-4db8-93e3-e5dfdedf4b21">

# round 2
<img width="1510" alt="round_2" src="https://github.com/prijatelilab/PrijateliTree/assets/25271399/245174af-ceb8-46ef-8faf-0c1deef27aab">

# end of game win
<img width="1512" alt="end_of_game_success" src="https://github.com/prijatelilab/PrijateliTree/assets/25271399/ff6ffca8-0b99-4426-92cb-622317e9fd5b">

# end of game loss
<img width="1512" alt="end_of_game_loss" src="https://github.com/prijatelilab/PrijateliTree/assets/25271399/d737427c-ee9a-4130-9a4f-7f536e162329">

**Comment by pepipandi** [comment]
# Aesthetic comments (by @pepipandi )

Going screen by screen:


1. Start of game
   * I would center the text in the middle of the page and make the text larger
   * Optional: colors over the red and blue colors
2. Round 1 
   * Center the text below Round
   * Optional: Add a little box/table around "Your ball"
3. Waiting on others
   * Center the text
4. Round 2
   * Center the text in the middle of the page
   * Add a little box/table around the list of guesses + your previous guess
   * Make the other's guesses larger (and same with your last guess both larger but the same size)
   * Make the other language smaller: "Your previous guess" "Look what others have guessed" can be a bit smaller, but again, keep them the same size
   * Make the final part "Guess the color of the bag" a bit separate from the suggestions (an empty line/row)
5. End Win
   * I would make You Won! larger
   * The Computer guessed---, you guessed-- can be in a little box/table and much larger
   * Maybe a line of space between the You won and the table/box saying their and the computer's guess
6. End Lost
   * Same from End Win

@anisfeld let me know if this looks good!

**Comment by anisfeld** [comment]
@pepipandi  Here is the language to send to CHRCR: https://uchicago.box.com/s/apbrrjcvtcqkzuq06ha6pqg4h1nmahfh

I'm ambivalent about the admin panel stuff. If you think it's okay to do everything in English we can keep it that way and not ask for those translations.

**Comment by anisfeld** [comment]
# Easily updated language

- [ ] Come up with solution to ensure easy and consistent updating of language. 

@FedericoDM  For this issue, we want to be able to update the language gracefully. I'm not sure what Michael did last time, but it's not easy for us to recreate from scratch.

One idea is to create the json on the fly from the spreadsheet. I think the idea of using unicode is appealing so as a first step you might convert the xls file to a csv with unicode or json with unicode. Or maybe you'll see the excel file works fine? 

```
# from main.py in vouchertracker
import json
import read_csv from pandas

language_file = read_csv("languages/languages.csv")
languages = language_file.set_index(keys="Keys").to_json()
languages = json.loads(languages)
```

# Clearer keys 


- [ ] Adjust old templates to match the new keys.

I've changed some of the keys in a way that I find more logical and organized the language in the spreadsheet so it follows the flow of the game. I hope this will reduce technical debt in the future, but requires adjusting the current templates

I should have kept the old keys in the spreadsheet and suggest your first step is to temporarily add a column of old keys to the spreadsheet so that you are sure to hit all of them.

**Comment by FedericoDM** [comment]
Translation processing is now automatic
