### ISSUE TITLE
Make Database upgrades

### ISSUE THREAD

**Issue by anisfeld** [prijatelilab/PrijateliTree#66]
## What Issue Are You Seeing or What Feature Needs To Be Added?

- [x] name_hidden to GameType
- [ ] Add Session table
   - [ ]  Start with Static practice game
- [ ] Add SessionPlayer table - with total # of points + # of correct answers

**Comment by michplunkett** [comment]
I'm aiming to have the latter two DB changes done tomorrow. I'll keep you updated.
