### ISSUE TITLE
Create diagrams for games using oTree vocabulary

### ISSUE THREAD

**Issue by michplunkett** [prijatelilab/PrijateliTree#7]
## What Issue Are You Seeing or What Feature Needs To Be Added?
Come with a diagram for each game using the oTree vocabulary (session, subsession, group, etc.).

## Are There Any Links That Would Be Helpful?
- Concepts: https://otree.readthedocs.io/en/latest/conceptual_overview.html

**Comment by FedericoDM** [comment]
Hmmm I get the architecture diagram, but I am having a bit of a hard time conceptualizing this task.. @michplunkett

**Comment by michplunkett** [comment]
I gotchu, @FedericoDM. What I'm looking for in this task is an adaptation of the games as Ari and Pepi have given them to us into the _Session_, _Subsession_, and _Page_ model. Given that we have three different kinds of games we can play (Integrated Network, Segregated Network, and Self-Selected Network), we should have three different types of _Sessions_. 

![image](https://github.com/prijatelilab/PrijateliTree/assets/5885605/f2b57010-8618-4fc4-a943-ec0e755dcb25)

If we take the Integrated Network game, we can think of each round as a _Subsession_ with each phase of that round as a page. Does that make sense?

**Comment by FedericoDM** [comment]
So this is more or less what I was thinking..

![image](https://github.com/prijatelilab/PrijateliTree/assets/67844597/ed3c6ff3-35e1-4fac-939b-c5a3299c596e)


It is tricky because they play the game several times in different modes (segregated network, then self selected network, etc)

**Comment by michplunkett** [comment]
Very nice! I appreciate the diagram creation as well, quite smooth.
