### ISSUE TITLE
Complete Heroku application configuration and deployment

### ISSUE THREAD

**Issue by michplunkett** [prijatelilab/PrijateliTree#78]
## What Issue Are You Seeing or What Feature Needs To Be Added?
- [x] Add the following environment variables: `ENV`, `LOGIN_SECRET_KEY`, `SQLALCHEMY_DATABASE_URI`
- [x] Sync repository with Heroku
- [x] Add Heroku script to make sure application runs
- [x] Make sure database user is setup
- [x] Confirm application runs on Heroku
- [x] Add tiered-logging ability: https://github.com/prijatelilab/PrijateliTree/pull/92
- [x] Add production users for @anisfeld and @pepipandi

**Comment by michplunkett** [comment]
@anisfeld I'll take care of this tomorrow, apologies for the delay.

**Comment by anisfeld** [comment]
Thanks for the update.
