### ISSUE TITLE
Write testing framework

### ISSUE THREAD

**Issue by anisfeld** [prijatelilab/PrijateliTree#83]

**Comment by anisfeld** [comment]
If you have time this would be great.  @michplunkett

**Comment by michplunkett** [comment]
I should be able to knock this out before EOD Thursday, starting on Wednesday.

**Comment by michplunkett** [comment]
Update: Gonna take care of it this weekend.

**Comment by michplunkett** [comment]
If you'd like more info how to test, etc., here's a good place to start: https://sqlmodel.tiangolo.com/tutorial/fastapi/tests/
