### ISSUE TITLE
Make MVP end of session page

### ISSUE THREAD

**Issue by anisfeld** [prijatelilab/PrijateliTree#99]
## What Issue Are You Seeing or What Feature Needs To Be Added?

Create a route that sends students to end screen.

We want an ending page as seen in the UX that says how much they earned and so forth 
- Use language from the json and let Pepi know if there are missing translations.

**Comment by anisfeld** [comment]
@FedericoDM  I'm linking to this page using the route  "/games/{{game_id}}/player/{{player_id}}/end_of_session"

**Comment by FedericoDM** [comment]
Got it! I am working on the template now @anisfeld

**Comment by FedericoDM** [comment]
Closed with #111
